### ISSUE TITLE
☄ Great Idea , but you should improve the interface 

### ISSUE THREAD

**Issue by yassinrais** [ablil/ideas-tab#1]
Hey ablil :) 

this is a cool idea, but you really should improve the design 

look try to inspire from https://dribbble.com/

and try to make things simple , colors , spaces etc..

Good luck !

**Comment by ablil** [comment]
A new desing has been deployed, hope you like it.

**Comment by yassinrais** [comment]
You can do more better, 
_the idea of having the sidebar is little hard in use , i mean we are more adapted to go up down fast more then left and right :)_ 

you should take care about small details , spacing and the padding etc ... 

in mobile you still have small issues in design

also about using firebase , if you are using nodejs hosting  you can just install a mongodb database , instead of using firebase

firebase is not a perfect solution, its become to expensive fast 

good luck and good job :)
